<upgrade>
    <settings>
        <setting>
            <group>general</group>
            <module_id>user</module_id>
            <is_hidden>0</is_hidden>
            <type>boolean</type>
            <var_name>enable_2step_verification</var_name>
            <phrase_var_name>setting_enable_2step_verification</phrase_var_name>
            <ordering>1</ordering>
            <version_id>4.3.0</version_id>
            <value>0</value>
        </setting>
    </settings>
</upgrade>
