<upgrade>
    <settings>
        <setting>
            <group>general</group>
            <module_id>user</module_id>
            <is_hidden>0</is_hidden>
            <type>boolean</type>
            <var_name>hide_recommended_user_block</var_name>
            <phrase_var_name>setting_hide_recommended_user_block</phrase_var_name>
            <ordering>15</ordering>
            <version_id>4.4.0</version_id>
            <value>0</value>
        </setting>
        <setting>
            <group />
            <module_id>user</module_id>
            <is_hidden>0</is_hidden>
            <type>boolean</type>
            <var_name>captcha_on_login</var_name>
            <phrase_var_name>setting_captcha_on_login</phrase_var_name>
            <ordering>16</ordering>
            <version_id>4.4.0</version_id>
            <value>0</value>
        </setting>
    </settings>
    <components>
        <component>
            <module_id>user</module_id>
            <component>welcome</component>
            <m_connection/>
            <module>user</module>
            <is_controller>0</is_controller>
            <is_block>1</is_block>
            <is_active>1</is_active>
            <value />
        </component>
    </components>
    <blocks>
        <block>
            <type_id>0</type_id>
            <m_connection>core.index-visitor</m_connection>
            <module_id>user</module_id>
            <component>welcome</component>
            <location>1</location>
            <is_active>1</is_active>
            <ordering>1</ordering>
            <disallow_access/>
            <can_move>0</can_move>
            <title><![CDATA[Welcome]]></title>
            <source_code/>
            <source_parsed/>
        </block>
    </blocks>
    <phpfox_update_settings>
        <setting>
            <group>time_stamps</group>
            <module_id>user</module_id>
            <is_hidden>0</is_hidden>
            <type>string</type>
            <var_name>user_dob_month_day_year</var_name>
            <phrase_var_name>setting_user_dob_month_day_year</phrase_var_name>
            <ordering>1</ordering>
            <version_id>3.0.0</version_id>
            <value>F j, Y</value>
        </setting>
        <setting>
            <group>time_stamps</group>
            <module_id>user</module_id>
            <is_hidden>0</is_hidden>
            <type>string</type>
            <var_name>user_dob_month_day</var_name>
            <phrase_var_name>setting_user_dob_month_day</phrase_var_name>
            <ordering>2</ordering>
            <version_id>3.0.0</version_id>
            <value>F j</value>
        </setting>
    </phpfox_update_settings>
</upgrade>
