<upgrade>
    <user_group_settings>
        <setting>
            <is_admin_setting>0</is_admin_setting>
            <module_id>ad</module_id>
            <type>boolean</type>
            <admin>true</admin>
            <user>false</user>
            <guest>false</guest>
            <staff>true</staff>
            <module>ad</module>
            <ordering>0</ordering>
            <value>ad_campaigns_must_be_approved_first</value>
        </setting>
    </user_group_settings>
</upgrade>