<upgrade>
	<settings>
		<setting>
			<group>formatting</group>
			<module_id>core</module_id>
			<is_hidden>0</is_hidden>
			<type>boolean</type>
			<var_name>allow_html_in_activity_feed</var_name>
			<phrase_var_name>setting_allow_html_in_activity_feed</phrase_var_name>
			<ordering>6</ordering>
			<version_id>3.0.0beta3</version_id>
			<value>0</value>
		</setting>
		<setting>
			<group>server_settings</group>
			<module_id>core</module_id>
			<is_hidden>0</is_hidden>
			<type>boolean</type>
			<var_name>disable_hash_bang_support</var_name>
			<phrase_var_name>setting_disable_hash_bang_support</phrase_var_name>
			<ordering>14</ordering>
			<version_id>3.0.0beta3</version_id>
			<value>0</value>
		</setting>
	</settings>
	<phpfox_update_settings>
		<setting>
			<group>formatting</group>
			<module_id>core</module_id>
			<is_hidden>1</is_hidden>
			<type>boolean</type>
			<var_name>enabled_edit_area</var_name>
			<phrase_var_name>setting_enabled_edit_area</phrase_var_name>
			<ordering>5</ordering>
			<version_id>2.0.7</version_id>
			<value>0</value>
		</setting>
	</phpfox_update_settings>
</upgrade>