<upgrade>
	<settings>
		<setting>
			<group>server_settings</group>
			<module_id>core</module_id>
			<is_hidden>0</is_hidden>
			<type>boolean</type>
			<var_name>include_master_files</var_name>
			<phrase_var_name>setting_include_master_files</phrase_var_name>
			<ordering>15</ordering>
			<version_id>3.6.0rc1</version_id>
			<value>0</value>
		</setting>
		<setting>
			<group>cache</group>
			<module_id>core</module_id>
			<is_hidden>0</is_hidden>
			<type>boolean</type>
			<var_name>defer_loading_user_images</var_name>
			<phrase_var_name>setting_defer_loading_user_images</phrase_var_name>
			<ordering>1</ordering>
			<version_id>3.6.0rc1</version_id>
			<value>0</value>
		</setting>
		<setting>
			<group>cache</group>
			<module_id>core</module_id>
			<is_hidden>0</is_hidden>
			<type>boolean</type>
			<var_name>defer_loading_images</var_name>
			<phrase_var_name>setting_defer_loading_images</phrase_var_name>
			<ordering>2</ordering>
			<version_id>3.6.0rc1</version_id>
			<value>0</value>
		</setting>
		<setting>
			<group>cache</group>
			<module_id>core</module_id>
			<is_hidden>0</is_hidden>
			<type>boolean</type>
			<var_name>keep_non_square_images</var_name>
			<phrase_var_name>setting_keep_non_square_images</phrase_var_name>
			<ordering>3</ordering>
			<version_id>3.6.0rc1</version_id>
			<value>1</value>
		</setting>
		<setting>
			<group>cache</group>
			<module_id>core</module_id>
			<is_hidden>0</is_hidden>
			<type>array</type>
			<var_name>controllers_to_load_delayed</var_name>
			<phrase_var_name>setting_controllers_to_load_delayed</phrase_var_name>
			<ordering>4</ordering>
			<version_id>3.6.0rc1</version_id>
			<value><![CDATA[s:8:"array();";]]></value>
		</setting>
		<setting>
			<group>cache</group>
			<module_id>core</module_id>
			<is_hidden>0</is_hidden>
			<type>boolean</type>
			<var_name>super_cache_system</var_name>
			<phrase_var_name>setting_super_cache_system</phrase_var_name>
			<ordering>5</ordering>
			<version_id>3.6.0rc1</version_id>
			<value>0</value>
		</setting>
		<setting>
			<group>cache</group>
			<module_id>core</module_id>
			<is_hidden>0</is_hidden>
			<type>boolean</type>
			<var_name>store_only_users_in_session</var_name>
			<phrase_var_name>setting_store_only_users_in_session</phrase_var_name>
			<ordering>6</ordering>
			<version_id>3.6.0rc1</version_id>
			<value>0</value>
		</setting>
		<setting>
			<group>cdn_content_delivery_network</group>
			<module_id>core</module_id>
			<is_hidden>0</is_hidden>
			<type>boolean</type>
			<var_name>push_jscss_to_cdn</var_name>
			<phrase_var_name>setting_push_jscss_to_cdn</phrase_var_name>
			<ordering>16</ordering>
			<version_id>3.6.0rc1</version_id>
			<value>0</value>
		</setting>
		<setting>
			<group>search_engine_optimization</group>
			<module_id>core</module_id>
			<is_hidden>0</is_hidden>
			<type>boolean</type>
			<var_name>include_site_title_all_pages</var_name>
			<phrase_var_name>setting_include_site_title_all_pages</phrase_var_name>
			<ordering>8</ordering>
			<version_id>3.6.0rc1</version_id>
			<value>0</value>
		</setting>
		<setting>
			<group>cache</group>
			<module_id>core</module_id>
			<is_hidden>0</is_hidden>
			<type>boolean</type>
			<var_name>force_404_check</var_name>
			<phrase_var_name>setting_force_404_check</phrase_var_name>
			<ordering>7</ordering>
			<version_id>3.6.0rc1</version_id>
			<value>0</value>
		</setting>
		<setting>
			<group>formatting</group>
			<module_id>core</module_id>
			<is_hidden>0</is_hidden>
			<type>boolean</type>
			<var_name>enable_html_purifier</var_name>
			<phrase_var_name>setting_enable_html_purifier</phrase_var_name>
			<ordering>8</ordering>
			<version_id>3.6.0rc1</version_id>
			<value>1</value>
		</setting>
		<setting>
			<group>security</group>
			<module_id>core</module_id>
			<is_hidden>0</is_hidden>
			<type>boolean</type>
			<var_name>use_custom_cookie_names</var_name>
			<phrase_var_name>setting_use_custom_cookie_names</phrase_var_name>
			<ordering>2</ordering>
			<version_id>3.6.0rc1</version_id>
			<value>0</value>
		</setting>
		<setting>
			<group>security</group>
			<module_id>core</module_id>
			<is_hidden>0</is_hidden>
			<type>string</type>
			<var_name>custom_cookie_names_hash</var_name>
			<phrase_var_name>setting_custom_cookie_names_hash</phrase_var_name>
			<ordering>3</ordering>
			<version_id>3.6.0rc1</version_id>
			<value>s6ks763s5h3)s</value>
		</setting>
		<setting>
			<group>security</group>
			<module_id>core</module_id>
			<is_hidden>0</is_hidden>
			<type>string</type>
			<var_name>protect_admincp_with_ips</var_name>
			<phrase_var_name>setting_protect_admincp_with_ips</phrase_var_name>
			<ordering>4</ordering>
			<version_id>3.6.0rc1</version_id>
			<value />
		</setting>
		<setting>
			<group>security</group>
			<module_id>core</module_id>
			<is_hidden>0</is_hidden>
			<type>boolean</type>
			<var_name>auth_user_via_session</var_name>
			<phrase_var_name>setting_auth_user_via_session</phrase_var_name>
			<ordering>5</ordering>
			<version_id>3.6.0rc1</version_id>
			<value>0</value>
		</setting>
		<setting>
			<group>cache</group>
			<module_id>core</module_id>
			<is_hidden>0</is_hidden>
			<type>boolean</type>
			<var_name>include_ip_sub_id_hash</var_name>
			<phrase_var_name>setting_include_ip_sub_id_hash</phrase_var_name>
			<ordering>8</ordering>
			<version_id>3.6.0rc1</version_id>
			<value>0</value>
		</setting>
		<setting>
			<group>security</group>
			<module_id>core</module_id>
			<is_hidden>0</is_hidden>
			<type>string</type>
			<var_name>id_hash_salt</var_name>
			<phrase_var_name>setting_id_hash_salt</phrase_var_name>
			<ordering>6</ordering>
			<version_id>3.6.0rc1</version_id>
			<value>iysduyt623rts</value>
		</setting>
		<setting>
			<group>security</group>
			<module_id>core</module_id>
			<is_hidden>0</is_hidden>
			<type>boolean</type>
			<var_name>check_body_for_text</var_name>
			<phrase_var_name>setting_check_body_for_text</phrase_var_name>
			<ordering>7</ordering>
			<version_id>3.6.0rc1</version_id>
			<value>0</value>
		</setting>
		<setting>
			<group>security</group>
			<module_id>core</module_id>
			<is_hidden>0</is_hidden>
			<type>string</type>
			<var_name>check_body_regex</var_name>
			<phrase_var_name>setting_check_body_regex</phrase_var_name>
			<ordering>8</ordering>
			<version_id>3.6.0rc1</version_id>
			<value>/oParams/i</value>
		</setting>
		<setting>
			<group>security</group>
			<module_id>core</module_id>
			<is_hidden>0</is_hidden>
			<type>string</type>
			<var_name>check_body_offline_message</var_name>
			<phrase_var_name>setting_check_body_offline_message</phrase_var_name>
			<ordering>9</ordering>
			<version_id>3.6.0rc1</version_id>
			<value>Site is under maintenance.</value>
		</setting>
		<setting>
			<group>security</group>
			<module_id>core</module_id>
			<is_hidden>0</is_hidden>
			<type>string</type>
			<var_name>check_body_header</var_name>
			<phrase_var_name>setting_check_body_header</phrase_var_name>
			<ordering>10</ordering>
			<version_id>3.6.0rc1</version_id>
			<value>HTTP/1.0 500 Internal Server Error</value>
		</setting>
		<setting>
			<group>formatting</group>
			<module_id>core</module_id>
			<is_hidden>0</is_hidden>
			<type>large_string</type>
			<var_name>html_purifier_allowed_html</var_name>
			<phrase_var_name>setting_html_purifier_allowed_html</phrase_var_name>
			<ordering>9</ordering>
			<version_id>3.6.0rc1</version_id>
			<value><![CDATA[br,p,em,u,ul,li,font,ol,div[class|style],span[style],blockquote,strike,b,strong,img[src|alt|class|height|width],a[href|rel],iframe[src|width|height|frameborder],object[width|height|data],param[name|value],embed[src|type|allowscriptaccess|allowfullscreen|width|height]]]></value>
		</setting>
		<setting>
			<group>formatting</group>
			<module_id>core</module_id>
			<is_hidden>0</is_hidden>
			<type>large_string</type>
			<var_name>html_purifier_allowed_iframes</var_name>
			<phrase_var_name>setting_html_purifier_allowed_iframes</phrase_var_name>
			<ordering>10</ordering>
			<version_id>3.6.0rc1</version_id>
			<value>%^http://(www.youtube.com/embed/|player.vimeo.com/video/)%</value>
		</setting>
	</settings>
	<setting_groups>
		<name>
			<module_id>core</module_id>
			<version_id>3.6.0rc1</version_id>
			<var_name>setting_group_security</var_name>
			<value>security</value>
		</name>
	</setting_groups>
</upgrade>