<upgrade>
	<settings>
		<setting>
			<group>registration</group>
			<module_id>core</module_id>
			<is_hidden>0</is_hidden>
			<type>boolean</type>
			<var_name>city_in_registration</var_name>
			<phrase_var_name>setting_city_in_registration</phrase_var_name>
			<ordering>17</ordering>
			<version_id>3.7.0beta1</version_id>
			<value>0</value>
		</setting>
	</settings>
</upgrade>