<upgrade>
    <settings>
        <setting>
            <group>ftp_account</group>
            <module_id>core</module_id>
            <is_hidden>0</is_hidden>
            <type>string</type>
            <var_name>ftp_host_name</var_name>
            <phrase_var_name>ftp_host_name</phrase_var_name>
            <ordering>2</ordering>
            <version_id>4.2.0</version_id>
            <value>localhost</value>
        </setting>
        <setting>
            <group>ftp_account</group>
            <module_id>core</module_id>
            <is_hidden>0</is_hidden>
            <type>string</type>
            <var_name>ftp_port</var_name>
            <phrase_var_name>ftp_port</phrase_var_name>
            <ordering>3</ordering>
            <version_id>4.2.0</version_id>
            <value>21</value>
        </setting>
        <setting>
            <group>ftp_account</group>
            <module_id>core</module_id>
            <is_hidden>0</is_hidden>
            <type>string</type>
            <var_name>ftp_user_name</var_name>
            <phrase_var_name>ftp_user_name</phrase_var_name>
            <ordering>4</ordering>
            <version_id>4.2.0</version_id>
            <value>username</value>
        </setting>
        <setting>
            <group>ftp_account</group>
            <module_id>core</module_id>
            <is_hidden>0</is_hidden>
            <type>string</type>
            <var_name>ftp_password</var_name>
            <phrase_var_name>ftp_password</phrase_var_name>
            <ordering>5</ordering>
            <version_id>4.2.0</version_id>
            <value>password</value>
        </setting>
        <setting>
            <group>ftp_account</group>
            <module_id>core</module_id>
            <is_hidden>0</is_hidden>
            <type>drop</type>
            <var_name>upload_method</var_name>
            <phrase_var_name>file_upload_method</phrase_var_name>
            <ordering>1</ordering>
            <version_id>4.2.0</version_id>
            <value><![CDATA[a:2:{s:7:"default";s:3:"ftp";s:6:"values";a:3:{i:0;s:11:"file_system";i:1;s:3:"ftp";i:2;s:8:"sftp_ssh";}}]]></value>
        </setting>
    </settings>
    <setting_groups>
        <name>
            <module_id>core</module_id>
            <version_id>4.2.0</version_id>
            <var_name>ftp_account</var_name>
            <value>ftp_account</value>
        </name>
    </setting_groups>
</upgrade>
