<upgrade>
    <crons>
        <cron>
            <module_id>core</module_id>
            <type_id>1</type_id>
            <every>1</every>
            <value><![CDATA[Phpfox_Queue::instance()->work();]]></value>
        </cron>
    </crons>
    <settings>
        <setting>
            <group>general</group>
            <module_id>core</module_id>
            <is_hidden>0</is_hidden>
            <type>boolean</type>
            <var_name>turn_off_full_ajax_mode</var_name>
            <phrase_var_name>setting_turn_off_full_ajax_mode</phrase_var_name>
            <ordering>1</ordering>
            <version_id>4.4.0</version_id>
            <value>false</value>
        </setting>
    </settings>
    <setting_groups>
        <name>
            <module_id>core</module_id>
            <version_id>4.4.0</version_id>
            <var_name>setting_group_time_stamps</var_name>
            <value>time_stamps</value>
        </name>
    </setting_groups>
    <phpfox_update_settings>
        <setting>
            <group>time_stamps</group>
            <module_id>core</module_id>
            <is_hidden>0</is_hidden>
            <type>string</type>
            <var_name>global_update_time</var_name>
            <phrase_var_name>setting_global_update_time</phrase_var_name>
            <ordering>1</ordering>
            <version_id>2.0.0alpha1</version_id>
            <value>F j, Y</value>
        </setting>
        <setting>
            <group>time_stamps</group>
            <module_id>core</module_id>
            <is_hidden>0</is_hidden>
            <type>string</type>
            <var_name>profile_time_stamps</var_name>
            <phrase_var_name>setting_profile_time_stamps</phrase_var_name>
            <ordering>8</ordering>
            <version_id>2.0.0alpha1</version_id>
            <value>F j, Y</value>
        </setting>
        <setting>
            <group>time_stamps</group>
            <module_id>core</module_id>
            <is_hidden>0</is_hidden>
            <type>string</type>
            <var_name>default_time_zone_offset</var_name>
            <phrase_var_name>setting_default_time_zone_offset</phrase_var_name>
            <ordering>0</ordering>
            <version_id>2.0.0alpha1</version_id>
            <value>0</value>
        </setting>
        <setting>
            <group>time_stamps</group>
            <module_id>core</module_id>
            <is_hidden>0</is_hidden>
            <type>boolean</type>
            <var_name>identify_dst</var_name>
            <phrase_var_name>setting_identify_dst</phrase_var_name>
            <ordering>9</ordering>
            <version_id>2.0.0beta5</version_id>
            <value>1</value>
        </setting>
        <setting>
            <group>time_stamps</group>
            <module_id>core</module_id>
            <is_hidden>0</is_hidden>
            <type>string</type>
            <var_name>extended_global_time_stamp</var_name>
            <phrase_var_name>setting_extended_global_time_stamp</phrase_var_name>
            <ordering>10</ordering>
            <version_id>2.0.0rc2</version_id>
            <value>M j, g:i a</value>
        </setting>
        <setting>
            <group>time_stamps</group>
            <module_id>core</module_id>
            <is_hidden>0</is_hidden>
            <type>drop</type>
            <var_name>date_field_order</var_name>
            <phrase_var_name>setting_date_field_order</phrase_var_name>
            <ordering>15</ordering>
            <version_id>3.0.0Beta1</version_id>
            <value><![CDATA[a:2:{s:7:"default";s:3:"MDY";s:6:"values";a:3:{i:0;s:3:"MDY";i:1;s:3:"DMY";i:2;s:3:"YMD";}}]]></value>
        </setting>
        <setting>
            <group>time_stamps</group>
            <module_id>core</module_id>
            <is_hidden>0</is_hidden>
            <type>boolean</type>
            <var_name>use_jquery_datepicker</var_name>
            <phrase_var_name>setting_use_jquery_datepicker</phrase_var_name>
            <ordering>16</ordering>
            <version_id>3.0.0Beta1</version_id>
            <value>1</value>
        </setting>
    </phpfox_update_settings>
    <tables><![CDATA[a:1:{s:15:"phpfox_cron_job";a:2:{s:7:"COLUMNS";a:6:{s:2:"id";a:4:{i:0;s:7:"UINT:11";i:1;N;i:2;s:14:"auto_increment";i:3;s:2:"NO";}s:10:"queue_name";a:4:{i:0;s:8:"VCHAR:50";i:1;s:7:"default";i:2;s:0:"";i:3;s:2:"NO";}s:4:"data";a:4:{i:0;s:4:"TEXT";i:1;N;i:2;s:0:"";i:3;s:2:"NO";}s:11:"expire_time";a:4:{i:0;s:7:"UINT:11";i:1;s:3:"600";i:2;s:0:"";i:3;s:2:"NO";}s:10:"is_running";a:4:{i:0;s:6:"TINT:1";i:1;s:1:"0";i:2;s:0:"";i:3;s:2:"NO";}s:8:"last_run";a:4:{i:0;s:7:"UINT:11";i:1;s:1:"0";i:2;s:0:"";i:3;s:2:"NO";}}s:11:"PRIMARY_KEY";s:2:"id";}}]]></tables>
</upgrade>