<upgrade>
    <setting_groups>
        <name>
            <module_id>core</module_id>
            <version_id>4.5.0</version_id>
            <var_name>setting_group_seo</var_name>
            <value>seo</value>
        </name>
    </setting_groups>
    <settings>
        <setting>
            <group>seo</group>
            <module_id>core</module_id>
            <is_hidden>0</is_hidden>
            <type>string</type>
            <var_name>google_plus_page_url</var_name>
            <phrase_var_name>setting_google_plus_page_url</phrase_var_name>
            <ordering>1</ordering>
            <version_id>4.5.0</version_id>
            <value />
        </setting>
    </settings>
</upgrade>