<upgrade>
    <setting_groups>
        <name>
            <module_id>core</module_id>
            <version_id>4.6.0</version_id>
            <var_name>setting_group_label_ssl</var_name>
            <value>ssl</value>
        </name>
    </setting_groups>
    <settings>
        <setting>
            <group>general</group>
            <module_id>core</module_id>
            <is_hidden>0</is_hidden>
            <type>drop</type>
            <var_name>paging_mode</var_name>
            <phrase_var_name>setting_paging_mode</phrase_var_name>
            <ordering>1</ordering>
            <version_id>4.6.0</version_id>
            <value><![CDATA[a:2:{s:7:"default";s:8:"loadmore";s:6:"values";a:3:{i:0;s:8:"loadmore";i:1;s:9:"next_prev";i:2;s:10:"pagination";}}]]></value>
        </setting>
    </settings>
    <settings>
        <setting>
            <group>registration</group>
            <module_id>core</module_id>
            <is_hidden>0</is_hidden>
            <type>string</type>
            <var_name>clickatell_api_key</var_name>
            <phrase_var_name>setting_clickatell_api_key</phrase_var_name>
            <ordering>1</ordering>
            <version_id>4.6.0</version_id>
            <value></value>
        </setting>
    </settings>
    <crons>
        <cron>
            <module_id>core</module_id>
            <type_id>2</type_id>
            <every>1</every>
            <value><![CDATA[Phpfox::getService('core.temp-file')->clean();]]></value>
        </cron>
        <cron>
            <module_id>core</module_id>
            <type_id>2</type_id>
            <every>1</every>
            <value><![CDATA[Phpfox::getService('admincp.maintain')->cronRemoveCache();]]></value>
        </cron>
    </crons>
</upgrade>