<?php

array_unshift($aBundleScripts, [
    'icofont.css'                                         => 'style_css',
    'font-awesome/css/font-awesome.min.css'               => 'style_css',
    'bootstrap-tokenfield.min.css'                        => 'style_css',
    'bootstrap.css'                                       => 'flavor_bootstrap',
    'boot.css'                                            => 'flavor_boot',
    'jquery.mCustomScrollbar.min.css'                     => 'style_css',
    'owl_carousel/owl.carousel.min.css'                   => 'style_css',
    'owl_carousel/owl.theme.default.min.css'              => 'style_css',
    'asBreadcrumbs.min.css'                               => 'style_css',
    'jquery/jquery.js'                                    => 'static_script',
    'jquery/ui.js'                                        => 'static_script',
    'jquery/plugin/jquery.nanoscroller.min.js'            => 'static_script',
    'bootstrap.js'                                        => 'static_script',
    'common.js'                                           => 'static_script',
    'main.js'                                             => 'static_script',
    'ajax.js'                                             => 'static_script',
    'thickbox/thickbox.js'                                => 'static_script',
    'search.js'                                           => 'module_friend',
    'progress.js'                                         => 'static_script',
    'nprogress.js'                                        => 'static_script',
    'quick_edit.js'                                       => 'static_script',
    'feed.js'                                             => 'module_feed',
    'dropzone.js'                                         => 'static_script',
    'jquery/plugin/bootstrap-tokenfield.min.js'           => 'static_script',
    'register.js'                                         => 'module_user',
    'jquery/plugin/jquery.mCustomScrollbar.concat.min.js' => 'static_script',
    'jquery/plugin/jquery.highlightFade.js'               => 'static_script',
    'jquery/plugin/jquery.scrollTo.js'                    => 'static_script',
    'user_info.js'                                        => 'static_script',
    'editor.js'                                           => 'static_script',

    'wysiwyg/default/core.js'          => 'static_script',
    'country.js'                       => 'module_core',
    'owl_carousel/owl.carousel.min.js' => 'static_script',
    'jquery-asBreadcrumbs.min.js'      => 'static_script',
]);