-- MySQL Script generated by MySQL Workbench
-- Wed Jan 31 13:23:41 2018
-- Model: Instapaint    Version: 1.0

-- Model created from basic phpFox installation. 

-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema instapaint
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema instapaint
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `instapaint` DEFAULT CHARACTER SET latin1 ;
USE `instapaint` ;

-- -----------------------------------------------------
-- Table `instapaint`.`phpfox_instapaint_frame_size`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `instapaint`.`phpfox_instapaint_frame_size` (
  `frame_size_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name_phrase` VARCHAR(255) NOT NULL,
  `price_usd` DECIMAL(6,2) UNSIGNED NOT NULL,
  PRIMARY KEY (`frame_size_id`),
  UNIQUE INDEX `name_phrase_UNIQUE` (`name_phrase` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `instapaint`.`phpfox_instapaint_frame_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `instapaint`.`phpfox_instapaint_frame_type` (
  `frame_type_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name_phrase` VARCHAR(255) NOT NULL,
  `price_usd` DECIMAL(6,2) UNSIGNED NOT NULL,
  PRIMARY KEY (`frame_type_id`),
  UNIQUE INDEX `name_phrase_UNIQUE` (`name_phrase` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `instapaint`.`phpfox_instapaint_shipping_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `instapaint`.`phpfox_instapaint_shipping_type` (
  `shipping_type_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name_phrase` VARCHAR(255) NOT NULL,
  `price_usd` DECIMAL(6,2) UNSIGNED NOT NULL,
  PRIMARY KEY (`shipping_type_id`),
  UNIQUE INDEX `name_phrase_UNIQUE` (`name_phrase` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `instapaint`.`phpfox_instapaint_discount`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `instapaint`.`phpfox_instapaint_discount` (
  `discount_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `coupon_code` VARCHAR(255) NULL,
  `expiration_date` DATETIME NULL,
  `discount_percentage` TINYINT(3) UNSIGNED NOT NULL,
  PRIMARY KEY (`discount_id`),
  INDEX `coupon_code_INDEX` (`coupon_code` ASC),
  INDEX `expiration_date_INDEX` (`expiration_date` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `instapaint`.`phpfox_instapaint_frame_type_discount`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `instapaint`.`phpfox_instapaint_frame_type_discount` (
  `frame_type_discount_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `discount_id` INT(10) UNSIGNED NOT NULL,
  `frame_type_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`frame_type_discount_id`),
  INDEX `fk_phpfox_instapaint_frame_type_discount_phpfox_instapaint__idx` (`discount_id` ASC),
  INDEX `fk_phpfox_instapaint_frame_type_discount_phpfox_instapaint__idx1` (`frame_type_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `instapaint`.`phpfox_instapaint_frame_size_discount`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `instapaint`.`phpfox_instapaint_frame_size_discount` (
  `frame_size_discount_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `discount_id` INT(10) UNSIGNED NOT NULL,
  `frame_size_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`frame_size_discount_id`),
  INDEX `fk_phpfox_instapaint_frame_size_discount_phpfox_instapaint__idx` (`discount_id` ASC),
  INDEX `fk_phpfox_instapaint_frame_size_discount_phpfox_instapaint__idx1` (`frame_size_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `instapaint`.`phpfox_instapaint_shipping_type_discount`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `instapaint`.`phpfox_instapaint_shipping_type_discount` (
  `shipping_type_discount_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `discount_id` INT(10) UNSIGNED NOT NULL,
  `shipping_type_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`shipping_type_discount_id`),
  INDEX `fk_phpfox_instapaint_shipping_type_discount_phpfox_instapai_idx` (`discount_id` ASC),
  INDEX `fk_phpfox_instapaint_shipping_type_discount_phpfox_instapai_idx1` (`shipping_type_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `instapaint`.`phpfox_instapaint_painter_approval_request`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `instapaint`.`phpfox_instapaint_painter_approval_request` (
  `approval_request_id` INT(10) NOT NULL AUTO_INCREMENT,
  `user_id` INT(10) UNSIGNED NOT NULL,
  `request_timestamp` INT(10) UNSIGNED NOT NULL,
  `is_approved` TINYINT NOT NULL,
  `approver_user_id` INT(10) UNSIGNED NULL,
  `approved_timestamp` INT(10) UNSIGNED NULL,
  PRIMARY KEY (`approval_request_id`),
  INDEX `approved` (`is_approved` ASC),
  INDEX `fk_phpfox_instapaint_painter_approval_request_phpfox_user1_idx` (`user_id` ASC),
  INDEX `fk_phpfox_instapaint_painter_approval_request_phpfox_user2_idx` (`approver_user_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `instapaint`.`phpfox_instapaint_order_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `instapaint`.`phpfox_instapaint_order_status` (
  `order_status_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name_phrase` VARCHAR(255) NOT NULL,
  `description_phrase` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`order_status_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `instapaint`.`phpfox_instapaint_address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `instapaint`.`phpfox_instapaint_address` (
  `address_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `client_user_id` INT(10) UNSIGNED NOT NULL,
  `country_iso` CHAR(2) NOT NULL,
  `full_name` TINYTEXT NOT NULL,
  `street_address` TINYTEXT NOT NULL,
  `street_address_2` TINYTEXT NULL,
  `city` TINYTEXT NOT NULL,
  `state_province_region` TINYTEXT NOT NULL,
  `zip_code` VARCHAR(16) NOT NULL,
  `phone_number` VARCHAR(16) NOT NULL,
  `security_access_code` VARCHAR(155) NULL,
  `can_receive_on_saturday` TINYINT UNSIGNED NOT NULL DEFAULT 1,
  `can_receive_on_sunday` TINYINT UNSIGNED NOT NULL DEFAULT 1,
  PRIMARY KEY (`address_id`),
  INDEX `fk_phpfox_instapaint_address_phpfox_user1_idx` (`client_user_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `instapaint`.`phpfox_instapaint_order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `instapaint`.`phpfox_instapaint_order` (
  `order_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `order_status_id` INT(10) UNSIGNED NOT NULL,
  `created_timestamp` INT(10) UNSIGNED NOT NULL,
  `updated_timestamp` INT(10) UNSIGNED NULL,
  `client_user_id` INT(10) UNSIGNED NOT NULL,
  `uptater_user_id` INT(10) UNSIGNED NULL,
  `shipping_address_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`order_id`),
  INDEX `fk_phpfox_instapaint_order_phpfox_instapaint_order_status1_idx` (`order_status_id` ASC),
  INDEX `fk_phpfox_instapaint_order_phpfox_instapaint_address1_idx` (`shipping_address_id` ASC),
  INDEX `fk_phpfox_instapaint_order_phpfox_user1_idx` (`client_user_id` ASC),
  INDEX `fk_phpfox_instapaint_order_phpfox_user2_idx` (`uptater_user_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `instapaint`.`phpfox_instapaint_invoice_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `instapaint`.`phpfox_instapaint_invoice_status` (
  `invoice_status_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name_phrase` VARCHAR(255) NOT NULL,
  `description_phrase` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`invoice_status_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `instapaint`.`phpfox_instapaint_invoice`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `instapaint`.`phpfox_instapaint_invoice` (
  `invoice_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `order_id` INT(10) UNSIGNED NOT NULL,
  `invoice_status_id` INT(10) UNSIGNED NOT NULL,
  `created_timestamp` INT(10) UNSIGNED NOT NULL,
  `updater_user_id` INT(10) UNSIGNED NULL,
  `updated_timestamp` INT(10) UNSIGNED NULL,
  PRIMARY KEY (`invoice_id`),
  INDEX `fk_phpfox_instapaint_invoice_phpfox_instapaint_invoice_stat_idx` (`invoice_status_id` ASC),
  INDEX `fk_phpfox_instapaint_invoice_phpfox_instapaint_order1_idx` (`order_id` ASC),
  INDEX `fk_phpfox_instapaint_invoice_phpfox_user1_idx` (`updater_user_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `instapaint`.`phpfox_instapaint_order_painter`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `instapaint`.`phpfox_instapaint_order_painter` (
  `order_painter_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `order_id` INT(10) UNSIGNED NOT NULL,
  `painter_user_id` INT(10) UNSIGNED NOT NULL,
  `assigned_by_user_id` INT(10) UNSIGNED NOT NULL,
  `assigned_timestamp` INT(10) UNSIGNED NOT NULL,
  `updater_user_id` INT(10) UNSIGNED NULL,
  `updated_timestamp` INT(10) UNSIGNED NULL,
  PRIMARY KEY (`order_painter_id`),
  INDEX `fk_phpfox_instapaint_order_painter_phpfox_instapaint_order1_idx` (`order_id` ASC),
  INDEX `fk_phpfox_instapaint_order_painter_phpfox_user1_idx` (`painter_user_id` ASC),
  INDEX `fk_phpfox_instapaint_order_painter_phpfox_user2_idx` (`updater_user_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `instapaint`.`phpfox_instapaint_order_cancellation_reason`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `instapaint`.`phpfox_instapaint_order_cancellation_reason` (
  `order_cancellation_reason_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `order_id` INT(10) UNSIGNED NOT NULL,
  `reason` TINYTEXT NOT NULL,
  PRIMARY KEY (`order_cancellation_reason_id`),
  INDEX `fk_phpfox_instapaint_order_cancellation_reason_phpfox_insta_idx` (`order_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `instapaint`.`phpfox_instapaint_order_fee_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `instapaint`.`phpfox_instapaint_order_fee_type` (
  `order_fee_type_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name_phrase` VARCHAR(255) NOT NULL,
  `description_phrase` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`order_fee_type_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `instapaint`.`phpfox_instapaint_order_fee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `instapaint`.`phpfox_instapaint_order_fee` (
  `order_fee_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `order_id` INT(10) UNSIGNED NOT NULL,
  `order_fee_type_id` INT(10) UNSIGNED NOT NULL,
  `amount_usd` DECIMAL(6,2) UNSIGNED NOT NULL,
  PRIMARY KEY (`order_fee_id`),
  INDEX `fk_phpfox_instapaint_order_fee_phpfox_instapaint_order_fee__idx` (`order_fee_type_id` ASC),
  INDEX `fk_phpfox_instapaint_order_fee_phpfox_instapaint_order1_idx` (`order_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `instapaint`.`phpfox_instapaint_order_discount`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `instapaint`.`phpfox_instapaint_order_discount` (
  `order_discount_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `order_id` INT(10) UNSIGNED NOT NULL,
  `discount_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`order_discount_id`),
  INDEX `fk_phpfox_instapaint_order_discount_phpfox_instapaint_disco_idx` (`discount_id` ASC),
  INDEX `fk_phpfox_instapaint_order_discount_phpfox_instapaint_order_idx` (`order_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `instapaint`.`phpfox_instapaint_order_shipping`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `instapaint`.`phpfox_instapaint_order_shipping` (
  `order_shipping_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `order_id` INT(10) UNSIGNED NOT NULL,
  `tracking_number` VARCHAR(45) NULL,
  `shipping_notes` TINYTEXT NULL,
  PRIMARY KEY (`order_shipping_id`),
  INDEX `fk_phpfox_instapaint_order_tracking_number_phpfox_instapain_idx` (`order_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `instapaint`.`phpfox_instapaint_default_address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `instapaint`.`phpfox_instapaint_default_address` (
  `default_address_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `client_user_id` INT(10) UNSIGNED NOT NULL,
  `address_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`default_address_id`),
  UNIQUE INDEX `client_user_id_UNIQUE` (`client_user_id` ASC),
  UNIQUE INDEX `address_id_UNIQUE` (`address_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `instapaint`.`phpfox_instapaint_payment_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `instapaint`.`phpfox_instapaint_payment_status` (
  `payment_status_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name_phrase` VARCHAR(255) NOT NULL,
  `description_phrase` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`payment_status_id`),
  UNIQUE INDEX `name_phrase_UNIQUE` (`name_phrase` ASC),
  UNIQUE INDEX `description_phrase_UNIQUE` (`description_phrase` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `instapaint`.`phpfox_instapaint_painter_payment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `instapaint`.`phpfox_instapaint_painter_payment` (
  `painter_payment_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `order_id` INT(10) UNSIGNED NOT NULL,
  `painter_user_id` INT(10) UNSIGNED NOT NULL,
  `payment_status_id` INT(10) UNSIGNED NOT NULL,
  `updater_user_id` INT(10) UNSIGNED NULL,
  `updated_timestamp` INT(10) UNSIGNED NULL,
  `amount_usd` DECIMAL(6,2) UNSIGNED NOT NULL,
  PRIMARY KEY (`painter_payment_id`),
  INDEX `fk_phpfox_instapaint_painter_payment_phpfox_instapaint_paym_idx` (`payment_status_id` ASC),
  INDEX `fk_phpfox_instapaint_painter_payment_phpfox_instapaint_orde_idx` (`order_id` ASC),
  INDEX `fk_phpfox_instapaint_painter_payment_phpfox_user1_idx` (`painter_user_id` ASC),
  INDEX `fk_phpfox_instapaint_painter_payment_phpfox_user2_idx` (`updater_user_id` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
