<upgrade>
	<user_group_settings>
		<setting>
			<is_admin_setting>0</is_admin_setting>
			<module_id>feed</module_id>
			<type>string</type>
			<admin>0</admin>
			<user>0</user>
			<guest>999999</guest>
			<staff>0</staff>
			<module>feed</module>
			<ordering>0</ordering>
			<value>feed_sponsor_price</value>
		</setting>
		<setting>
			<is_admin_setting>0</is_admin_setting>
			<module_id>feed</module_id>
			<type>boolean</type>
			<admin>true</admin>
			<user>false</user>
			<guest>false</guest>
			<staff>false</staff>
			<module>feed</module>
			<ordering>0</ordering>
			<value>can_sponsor_feed</value>
		</setting>
		<setting>
			<is_admin_setting>0</is_admin_setting>
			<module_id>feed</module_id>
			<type>boolean</type>
			<admin>true</admin>
			<user>true</user>
			<guest>true</guest>
			<staff>true</staff>
			<module>feed</module>
			<ordering>0</ordering>
			<value>auto_publish_sponsored_item</value>
		</setting>
		<setting>
			<is_admin_setting>0</is_admin_setting>
			<module_id>feed</module_id>
			<type>boolean</type>
			<admin>false</admin>
			<user>false</user>
			<guest>false</guest>
			<staff>false</staff>
			<module>feed</module>
			<ordering>0</ordering>
			<value>can_sponsor_feeds</value>
		</setting>
	</user_group_settings>
</upgrade>