<upgrade>
    <phpfox_update_settings>
        <setting>
            <group />
            <module_id>feed</module_id>
            <is_hidden>0</is_hidden>
            <type>integer</type>
            <var_name>refresh_activity_feed</var_name>
            <phrase_var_name>setting_refresh_activity_feed</phrase_var_name>
            <ordering>1</ordering>
            <version_id>3.0.0beta1</version_id>
            <value>60</value>
        </setting>
        <setting>
            <group>time_stamps</group>
            <module_id>feed</module_id>
            <is_hidden>0</is_hidden>
            <type>string</type>
            <var_name>feed_display_time_stamp</var_name>
            <phrase_var_name>setting_feed_display_time_stamp</phrase_var_name>
            <ordering>1</ordering>
            <version_id>2.0.0alpha3</version_id>
            <value>F j, Y g:i a</value>
        </setting>
    </phpfox_update_settings>
    <settings>
        <setting>
            <group />
            <module_id>feed</module_id>
            <is_hidden>0</is_hidden>
            <type>boolean</type>
            <var_name>allow_choose_sort_on_feeds</var_name>
            <phrase_var_name>setting_allow_choose_sort_on_feeds</phrase_var_name>
            <ordering>1</ordering>
            <version_id>4.4.0</version_id>
            <value>1</value>
        </setting>
    </settings>
</upgrade>