<upgrade>
    <phpfox_update_settings>
        <setting>
            <group />
            <module_id>track</module_id>
            <is_hidden>1</is_hidden>
            <type>integer</type>
            <var_name>cache_recently_viewed_by_timeout</var_name>
            <phrase_var_name>setting_cache_recently_viewed_by_timeout</phrase_var_name>
            <ordering>1</ordering>
            <version_id>3.6.0rc1</version_id>
            <value>0</value>
        </setting>
        <setting>
            <group />
            <module_id>track</module_id>
            <is_hidden>1</is_hidden>
            <type>integer</type>
            <var_name>cache_allow_recurrent_visit</var_name>
            <phrase_var_name>setting_cache_allow_recurrent_visit</phrase_var_name>
            <ordering>2</ordering>
            <version_id>3.6.0rc1</version_id>
            <value>0</value>
        </setting>
    </phpfox_update_settings>
    <settings>
        <setting>
            <group/>
            <module_id>track</module_id>
            <is_hidden>0</is_hidden>
            <type>boolean</type>
            <var_name>unique_viewers_counter</var_name>
            <phrase_var_name>setting_unique_viewers_counter</phrase_var_name>
            <ordering>2</ordering>
            <version_id>4.5.0</version_id>
            <value>1</value>
        </setting>
    </settings>
</upgrade>